apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: event-booking
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/Faruq2991/event-booking-system"
    targetRevision: HEAD
    path: event-booking-app
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
    syncPolicy: 
      automated:
        prune: true
        selfHeal: true