# templates/services.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-booking-app.fullname" . }}-backend
  labels:
    {{- include "event-booking-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "event-booking-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "event-booking-app.fullname" . }}-frontend
  labels:
    {{- include "event-booking-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "event-booking-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend