image:
  repository: faruq2991/event-booking-system
  tag: 81bd713
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: true
  className: "nginx"  # or your ingress controller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: event-booking.local
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: event-booking-backend
              port: 8080
        - path: /
          pathType: Prefix
          backend:
            service:
              name: event-booking-frontend
              port: 80

# Global settings
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  enabled: false
autoscaling:
  enabled: false
