<<<<<<< HEAD
image:
  repository: faruq2991/event-booking-system
  tag: 9f35b44
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
=======
# Backend configuration
backend:
  image:
    repository: faruq2991/event-booking-backend
    tag: ""
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8080
  replicaCount: 1

# Frontend configuration
frontend:
  image:
    repository: faruq2991/event-booking-frontend
    tag: ""
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  replicaCount: 1

# Ingress configuration to route traffic
>>>>>>> 7211559 (feat: update the helm chart templates.)
ingress:
  enabled: true
  className: "nginx"  # or your ingress controller
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: event-booking.local
      paths:
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: event-booking-backend
              port: 8080
        - path: /
          pathType: Prefix
          backend:
            service:
              name: event-booking-frontend
              port: 80

# Global settings
nameOverride: ""
fullnameOverride: ""
serviceAccount:
<<<<<<< HEAD
  enabled: false
autoscaling:
  enabled: false
=======
  create: true
  annotations: {}
  name: ""
>>>>>>> 7211559 (feat: update the helm chart templates.)
