name: Dev CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set SHORT_SHA
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

    
      - name: Build Backend
        run: docker build -t faruq96/event-booking-backend:${{ env.SHORT_SHA }} -f cmd/Dockerfile .

      - name: Push Backend Image
        run: docker push faruq96/event-booking-backend:${{ env.SHORT_SHA }}

      - name: Build Frontend
        run: docker build -t faruq96/event-booking-frontend:${{ env.SHORT_SHA }} -f web/Dockerfile web

      - name: Push Frontend Image
        run: docker push faruq96/event-booking-frontend:${{ env.SHORT_SHA }}

      - name: Configure git Author
        run: |
          git config --local user.email "faruqadam.93@gmail.com"
          git config --local user.name "Faruq2991"

      - name: Update helm chart with new image tag
        run: |
          sed -i "s/tag:.*/tag: ${{ env.SHORT_SHA }}/" ./event-booking/values.yaml
          git add ./event-booking/values.yaml
          git commit -m "Update image tag to ${{env.SHORT_SHA}}"
          git push


      - name: Success Confirmation
        run: echo "Build and push completed successfully!"