name: Dev CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.EVENT_BOOKING_TOKEN }}

      - name: Set SHORT_SHA
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Backend
      - name: Build Backend
        run: docker build -t faruq96/event-booking-backend:${{ env.SHORT_SHA }} -f cmd/Dockerfile .

      - name: Push Backend Image
        run: docker push faruq96/event-booking-backend:${{ env.SHORT_SHA }}

      # Build Frontend
      - name: Build Frontend
        run: docker build -t faruq96/event-booking-frontend:${{ env.SHORT_SHA }} -f web/Dockerfile web

      - name: Push Frontend Image
        run: docker push faruq96/event-booking-frontend:${{ env.SHORT_SHA }}

      - name: Configure git Author
        run: |
          git config --local user.email "faruqadam.92@gmail.com"
          git config --local user.name "Faruq2991"

      # Update both backend and frontend tags
      - name: Update helm chart with new image tags
        run: |
          sed -i "s/^\([[:space:]]*tag:\).*/\1 ${{ env.SHORT_SHA }}/" ./event-booking-app/values.yaml
          git add ./event-booking-app/values.yaml
          git commit -m "Update image tags to ${{env.SHORT_SHA}}"
          git push

      - name: Success Confirmation
        run: echo "Build and push completed successfully!"